# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: NucleosMapsBundle
  description: 📍 This bundle provides simple map rendering in symfony application.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, maps, googlemaps, openstreetmap, sonata, sonata-block

branches:
  - name: main
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Webpack build"
          - "Coding Standards (7.4)"
          - "Static Code Analysis (7.4)"
          - "Test (PHP 7.3, symfony 4.4, lowest)"
          - "Test (PHP 7.3, symfony 5.1, lowest)"
          - "Test (PHP 7.3, symfony 4.4, highest)"
          - "Test (PHP 7.3, symfony 5.1, highest)"
          - "Test (PHP 7.4, symfony 4.4, lowest)"
          - "Test (PHP 7.4, symfony 5.1, lowest)"
          - "Test (PHP 7.4, symfony 4.4, highest)"
          - "Test (PHP 7.4, symfony 5.1, highest)"
          - "Code Coverage (7.4)"
          - "Mutation Tests (7.4)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
